function [x_s, x_e, y_s, y_e] = kp2tp(dir_vec,p,z_s,z_e)
x_s = ((z_s - p(:,3))./...
    dir_vec(:,3)).*dir_vec(:,1) + p(:,1);
x_e = ((z_e - p(:,3))./...
    dir_vec(:,3)).*dir_vec(:,1) + p(:,1);
y_s = ((z_s - p(:,3))./...
    dir_vec(:,3)).*dir_vec(:,2) + p(:,2);
y_e = ((z_e - p(:,3))./...
    dir_vec(:,3)).*dir_vec(:,2) + p(:,2);
