function [norm_dir_vec, p0] = line2kd(A, B, C, D)
dir_vec = cross([A(:, 1), B(:, 1), C(:, 1)],...
                [A(:, 2), B(:, 2), C(:, 2)]);
norm_dir_vec = dir_vec ./ (sqrt(sum(dir_vec.*dir_vec,2))*ones(1,3));

p0 = [(B(:, 2) .* D(:, 1) - B(:, 1) .* D(:, 2)) ./ (A(:, 2) .* B(:, 1) - A(:, 1) .* B(:, 2)), ...
      (A(:, 2) .* D(:, 1) - A(:, 1) .* D(:, 2)) ./ (A(:, 1) .* B(:, 2) - A(:, 2) .* B(:, 1)), ...
                zeros(size(A, 1),1)];

